#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & swayosd-server & fcitx5  & vicinae server & 
# exec-once = waybar & swayosd-server & fcitx5  & vicinae server & mpvpaper DP-1 -o "no-audio --loop-playlist" Downloads/videoplayback.webm 

# Workspace Autolaunch
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] $terminal
exec-once = [workspace 11 silent] spotify
exec-once = [workspace 12 silent] ticktick
# workspace 20 used for hypridle
exec-once = hyprctl dispatch workspace 3
